title: "Tempus Lunae"
email: "umbra.aeterna.labs@gmail.com"
author: "Umbra Aeterna Labs"
description: "A moon phase and mushroom farming utility for Project: Gorgon"
repo: "https://github.com/Umbra-Aeterna-Labs/tempus-lunae"
github_user: "chrismabon"
github_repo: "umbra-aeterna-labs/tempus-lunae"
org_website: "https://linktr.ee/umbra_aeterna"
twitter: "https://ual.life/twgh"
twitch: "https://ual.life/tvgh"
youtube: "https://ual.life/ytgh"
instagram: "https://ual.life/iggh"
tiktok: "https://ual.life/tkgh"
